const mockMoviesArray = [
  {
    adult: false,
    backdrop_path: "/3qg8DpMjS84tzB7VhqeeZyQM9Ly.jpg",
    genre_ids: [18, 9648, 53],
    id: 117,
    original_language: "en",
    original_title: "Vertigo",
    overview: "A retired San Francisco detective suffering from acrophobia investigates the strange activities of an old friend's wife, all the while becoming dangerously obsessed with her.",
    popularity: 16.358,
    poster_path: "/hUzeosd33nzE5MCNsZxCGEKTXaQ.jpg",
    release_date: "1958-05-28",
    title: "Vertigo",
    video: false,
    vote_average: 8.3,
    vote_count: 2923,
  },  
  {
    adult: false,
    backdrop_path: "/o8W9E01FvZDQ2CJY5hNiXHV9JGg.jpg",
    genre_ids: [12, 16, 10751, 14],
    id: 10881,
    original_language: "en",
    original_title: "Pinocchio",
    overview: "Lonely toymaker Geppetto has his wishes answered when the Blue Fairy arrives to bring his wooden puppet Pinocchio to life. Before becoming a real boy, however, Pinocchio must prove he's worthy as he sets off on an adventure with his whistling sidekick and conscience, Jiminy Cricket.",
    popularity: 16.464,
    poster_path: "/fP9XDNkGq1Yu3kM2JN87kxTtvVq.jpg",
    release_date: "1940-02-23",
    title: "Pinocchio",
    video: false,
    vote_average: 7.1,
    vote_count: 3039,
  },
  {
    adult: false,
    backdrop_path: "/pKawqrtCBMmxarft7o1LbEynys7.jpg",
    genre_ids: [10752, 18, 28],
    id: 228150,
    original_language: "en",
    original_title: "Fury",
    overview: "Last months of World War II in April 1945. As the Allies make their final push in the European Theater, a battle-hardened U.S. Army sergeant in the 2nd Armored Division named Wardaddy commands a Sherman tank called \"Fury\" and its five-man crew on a deadly mission behind enemy lines. Outnumbered and outgunned, Wardaddy and his men face overwhelming odds in their heroic attempts to strike at the heart of Nazi Germany.",
    popularity: 28.398,
    poster_path: "/pfte7wdMobMF4CVHuOxyu6oqeeA.jpg",
    release_date: "2014-10-15",
    title: "Fury",
    video: false,
    vote_average: 7.5,
    vote_count: 7868,
  },
  {
    adult: false,
    backdrop_path: "/nLudS9ziR6UuEFbHEIqxyU5w6fs.jpg",
    genre_ids: [12, 18],
    id: 66728,
    original_language: "en",
    original_title: "Cast Away",
    overview: "Chuck, a top international manager for FedEx, and Kelly, a Ph.D. student, are in love and heading towards marriage. Then Chuck's plane to Malaysia crashes into the Pacific Ocean, leaving him stranded on a deserted island with only a volleyball named Wilson for company. Will he ever return to woman he loves and his former life?",
    popularity: 37.738,
    poster_path: "/pwlKo6sDCtTBSRtKNKrtmrZYpnT.jpg",
    release_date: "2000-12-22",
    title: "Cast Away",
    video: false,
    vote_average: 7.8,
    vote_count: 9819
  }
];

module.exports = {
  mockMoviesArray,
};
